version: '3'
services:
  redis:
    image: redis:alpine
    container_name: breet-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}